apiVersion: apps/v1
kind: Deployment
metadata:
  name: blue
spec:
  replicas: 2
  selector: # Telling the Deployment object how to / which manage pods
    matchLabels:
      app: app
      version: blue
  template: # This is how pods are created
    metadata:
      labels:
        app: app
        version: blue
    
    spec:
      containers:
        - name: nginx
          image: nginx:stable-alpine3.23-perl
        
          # readinessProbe:
          #   httpGet:
          #     path: /
          #     port: 80
          #   initialDelaySeconds: 1
          #   periodSeconds: 10
          #   failureThreshold: 3
          
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 1
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3


