apiVersion: apps/v1
kind: Deployment
metadata:
  name: canary-deployment
spec:
  replicas: 2
  selector: # Telling the Deployment object how to / which manage pods
    matchLabels:
      app: canary-app
      version: canary
  template: # This is how pods are created
    metadata:
      labels:
        app: canary-app
        version: canary
    
    spec:
      containers:
        - name: nginx
          image: nginx:alpine
          ports:
            - containerPort: 80
          volumeMounts:
            - name: nginx-config
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
      volumes:
        - name: nginx-config
          configMap:
            name: nginx-canary-config